### ISSUE TITLE
[Bug]: Bot degrades packages 

### ISSUE THREAD

**Issue by Yisus7u7** [termux-desktop/x11-packages#1]
### Problem description

@Maxython The bot is degrading the packages.

**Comment by Maxython** [comment]
Thank you for noticing this issue, but I can't fix or improve right now due to personal issues and a lot of work lately.  I [suggested](https://github.com/termux/termux-packages/discussions/9341) to the termux developers that they create packages in the pacman format in the "main" repo (that is, in termux/termux-packages, termux/x11-packages and termux/termux-root-packages).  

As soon as I am more or less free, I will deal with this issue.

**Comment by Yisus7u7** [comment]
@Maxython I will change the name of the organization for many reasons. 

But don't worry, you can continue to use this repository y

**Comment by Maxython** [comment]
Closing, since auto-update is now permanently disabled in this repository.
